### ISSUE TITLE
Doesn't hot reload

### ISSUE THREAD

**Issue by lukepighetti** [fedorenkoalex/Flutter-GraphWidget#1]
This widget doesn't respond to hot reloading, do you happen to know if this is a local issue or if it's an issue with this package? Thanks for your time.

**Comment by fedorenkoalex** [comment]
Hi @lukepighetti . I think i fixed this issue, please check in latest version https://pub.dev/packages/graph_widget#-readme-tab-

Thank you for your feedback.
